# -*- coding: utf-8 -*-
"""2.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nb5Trja1Hzcvk58Q0WtdrivPmx4lvmlr
"""

import re
import json

with open('corpus.json', 'r') as f:
    data = json.loads(f.readline())

for post in range(5):
    print(data[str(post)]['post_text'])
    print('')
    print('**************************************************************************')
    print('')

pattern = r'\n'
for post in data:
    data[post]['post_text'] = re.sub(pattern, ' ', data[post]['post_text'])

pattern = r'#\w+@\w+'
for post in data:
    data[post]['post_text'] = re.sub(pattern, '', data[post]['post_text'])

pattern = r'#\w+'
for post in data:
    data[post]['post_text'] = re.sub(pattern, '', data[post]['post_text'])

pattern = r'http\S+'
for post in data:
    data[post]['post_text'] = re.sub(pattern, '', data[post]['post_text'], flags=re.MULTILINE)

pattern = r'[^a-zA-Zа-яёА-ЯЁ\s\d!"#$%&/\\\\\'\(\)\*\+,\-\.:;<=>\?@\[\]^_`{|}~]+'
for post in data:
    data[post]['post_text'] = re.sub(pattern, '', data[post]['post_text'])

pattern = r'id\d+'
for post in data:
    data[post]['post_text'] = re.sub(pattern, '', data[post]['post_text'])

pattern = r'club\d+'
for post in data:
    data[post]['post_text'] = re.sub(pattern, '', data[post]['post_text'])

pattern = r'\|'
for post in data:
    data[post]['post_text'] = re.sub(pattern, '', data[post]['post_text'])

pattern = r'\s+'
for post in data:
    data[post]['post_text'] = re.sub(pattern, ' ', data[post]['post_text'])

for post in range(5):
    print(data[str(post)]['post_text'])
    print('')
    print('**************************************************************************')
    print('')

with open("clean_corpus.json", "w") as f:
    json.dump(data, f, ensure_ascii=False)